### ISSUE TITLE
Images created from Android Q Beta 1 won't mount

### ISSUE THREAD

**Issue by gittastic** [anestisb/android-simg2img#17] opened 2019-03-14 11:25 UTC
Firstly, thanks for the useful utility. Has served me well for a couple of years.

Today I'm trying to mount a raw image from the Android Q Beta 1 for the 2016 Pixel XL released today.

"simg2img system.img sys.raw" seems to work ok with no errors.

"mount -t ext4 -o loop sys.raw sys/" gives following error:

`mount: wrong fs type, bad option, bad superblock on /dev/loop0,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail  or so`

Syslog has this message:

`EXT4-fs (loop0): couldn't mount RDWR
 because of unsupported optional features (4000)`

I understand there are some changes in the way partitions are mounted in Android Q so I'm not too sure if this is a simg2img issue or not. Apologies if not.

**Comment by vasishath** [comment] 2019-03-14 12:51
The only visible difference I found is "huge files" flag in these images

**Comment by anestisb** [comment] 2019-03-25 06:16
@gittastic thanks for reporting. I'll have a look at the current libsparse commits in Android-Q beta branches in AOSP and try to resolve.

**Comment by icew4y** [comment] 2019-06-19 14:59
> Firstly, thanks for the useful utility. Has served me well for a couple of years.
> 
> Today I'm trying to mount a raw image from the Android Q Beta 1 for the 2016 Pixel XL released today.
> 
> "simg2img system.img sys.raw" seems to work ok with no errors.
> 
> "mount -t ext4 -o loop sys.raw sys/" gives following error:
> 
> `mount: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error In some cases useful info is found in syslog - try dmesg | tail or so`
> 
> Syslog has this message:
> 
> `EXT4-fs (loop0): couldn't mount RDWR because of unsupported optional features (4000)`
> 
> I understand there are some changes in the way partitions are mounted in Android Q so I'm not too sure if this is a simg2img issue or not. Apologies if not.

did you solve this problem,i got this error too.

**Comment by anestisb** [comment] 2019-06-21 06:38
No. I haven't found the time yet to work the Android Q support.

**Comment by XuLee4322** [comment] 2019-10-18 07:13
Any updates? same issue while using Android10 GSI

**Comment by protonchang** [comment] 2019-10-31 09:54
@XuLee4322 @gittastic 
Just mount it with ``` -o ro ```
It still works if you mount it as read-only

**Comment by gittastic** [comment] 2019-11-01 04:49
@protonchang that worked, many thanks!

**Comment by XuLee4322** [comment] 2019-11-04 06:28
@anestisb  but i want to mount it as "rw", not worked.

**Comment by anestisb** [comment] 2019-11-05 09:51
Should be fixed in latest master. Please pull latest version and try again.

**Closed by anestisb** 2019-11-05 09:51 UTC
Labels: android-q

**Comment by eraxillan** [comment] 2020-02-19 15:54
@anestisb hello, thanks for useful utility!

I just want to clarify: can current `simg2img` version can mount Android Q images in `rw`-mode?   
As one can understand from [that twit](https://twitter.com/topjohnwu/status/1170404631865778177), it can't just by design of ext4 dedup fs.   

Is it true?
If so, at least READMEs/wiki should be updated.

[Link to vendor.img to check](https://drive.google.com/file/d/1oxd0Agrxo9HLnyzPGdo1yw3DKsvK-aV_/view?usp=sharing)

**Comment by sooorajjj** [comment] 2021-05-26 07:44
Yes just run `simg2img` on system/vendor image to create unsparse image 
can be found in out  `Q/out/soong/host/linux-x86/bin/simg2img` or just buildit https://github.com/anestisb/android-simg2img

Now you will be able to run `mount -t ext4 -o ro system.img sys/`

**Comment by trilean** [comment] 2021-07-08 12:21
Sorry to bump an already closed issue. But was this ever resolved? I've just tried the latest git version of `simg2img` on Ubuntu 20.04 and I get this exact error. #27 also doesn't mention a real solution other than mounting read-only. This is not an option for me, since I have to modify the image. Thanks!

**Comment by MichisDevelopments** [comment] 2022-04-18 12:02
Maybe the solution is to detect the beginning of the file system within the img-file with binwalk.

```
#> binwalk super_raw.img|head -10

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
1048576       0x100000        Linux EXT filesystem, blocks count: 276183, image size: 282811392, rev 1.0, ext2 filesystem data, UUID=8794f4fa-90ce-433a-9f3b-c8465c625c62, volume name "/"
283974643     0x10ED1BF3      mcrypt 2.2 encrypted data, algorithm: blowfish-448, mode: CBC, keymode: 8bit
```
In the next step mount it with a offset parameter:
`mount -t auto -o loop,offset=0x100000 super_raw.img /mnt`

This should result in
```#> cd /mnt
#> ls -al
total 112
drwxr-xr-x. 24 root    root     4096 Apr 15  2021 .
drwxr-xr-x  22 root    root     4096 Mär 22 12:11 ..
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 acct
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 apex
lrw-r--r--.  1 root    root       11 Apr 15  2021 bin -> /system/bin
lrw-r--r--.  1 root    root       50 Apr 15  2021 bugreports -> /data/user_de/0/com.android.shell/files/bugreports
drwxrwx---.  2 michael    2001  4096 Apr 15  2021 cache
dr-xr-xr-x.  2 root    root     4096 Apr 15  2021 config
lrw-r--r--.  1 root    root       17 Apr 15  2021 d -> /sys/kernel/debug
drwxrwx--x.  2 michael michael  4096 Apr 15  2021 data
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 data_mirror
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 debug_ramdisk
lrw-------.  1 root    root       23 Apr 15  2021 default.prop -> system/etc/prop.default
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 dev
lrw-r--r--.  1 root    root       11 Apr 15  2021 etc -> /system/etc
lrwxr-x---.  1 root       2000    16 Apr 15  2021 init -> /system/bin/init
-rwxr-x---.  1 root       2000  2279 Apr 15  2021 init.environ.rc
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 linkerconfig
drwx------.  2 root    root    16384 Apr 15  2021 lost+found
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 metadata
drwxr-xr-x.  3 root    michael  4096 Apr 15  2021 mnt
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 odm
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 oem
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 proc
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 product
drwxr-xr-x.  3 root    root     4096 Apr 15  2021 res
lrw-r--r--.  1 root    root       21 Apr 15  2021 sdcard -> /storage/self/primary
drwxr-x--x.  2 root       1028  4096 Apr 15  2021 storage
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 sys
drwxr-xr-x. 15 root    root     4096 Apr 15  2021 system
drwxr-xr-x.  2 root    root     4096 Apr 15  2021 system_ext
drwxr-xr-x.  2 root       2000  4096 Apr 15  2021 vendor
```
