### ISSUE TITLE
Trim empty space on img2simg

### ISSUE THREAD

**Issue by dgadelha** [anestisb/android-simg2img#2] opened 2016-01-06 08:13 UTC
When using a 'dd' image of a system with img2simg, the final result is same size of 'dd' image.
img2simg should trim the empty space to make the file 'sparse'.

**Comment by anestisb** [comment] 2016-01-06 10:58
Do have you something more specific since I cannot reproduce.

```
anestisb@khaos:[tmp]: simg2img system.img system.img.raw
anestisb@khaos:[tmp]: img2simg system.img.raw system.img.sparse
anestisb@khaos:[tmp]: du system*
844728	system.img
2097152	system.img.raw
804608	system.img.sparse
anestisb@khaos:[tmp]: file system*
system.img:        Android sparse image, version: 1.0, Total of 262144 4096-byte output blocks in 1593 input chunks.
system.img.raw:    Linux rev 1.0 ext4 filesystem data, UUID=da594c53-9beb-f85c-85c5-cedf76546f7a, volume name "system" (extents) (large files)
system.img.sparse: Android sparse image, version: 1.0, Total of 262144 4096-byte output blocks in 408 input chunks.
```

**Comment by dgadelha** [comment] 2016-01-06 23:06
To reproduce, you need to:
1- On your device, create a raw image of your system partition using dd
=> dd if=/dev/block/by-name/system of=/sdcard/system.raw.img bs=1024
2- Use img2simg with that image
=> img2simg system.raw.img system.img
3- Check the result. Almost same size.

**Comment by dgadelha** [comment] 2016-01-06 23:08
FIXED using fstrim on device before using dd.

**Comment by dgadelha** [comment] 2016-01-06 23:38
The result file is not a valid sparse image.
Droidboot says:
    RECEIVE DATA...
    FLASH system 958422636 bytes...
    E:Unknown chunk type
       failed: Bad file number
    E:system flash failed!
    FLASH FAILED!

**Comment by anestisb** [comment] 2016-01-07 08:22
Still cannot reproduce. Seems that something is specific to your environment. Since "block/by-name" nodes are softlinks prefer to resolve it and then dd against that in case your toolbox/busybox implementation is misbehaving with softlinks. If this doesn't help you need to trace back if the error is in the raw export or the sparse convert.

You might also need to check if your device is not using the default block sizes so you need to explicitly define it as an argument to img2simg tool.

```
anestisb@khaos:[tmp]: adbWrap shell "mount | grep system"
/dev/block/mmcblk0p25 on /system type ext4 (rw,seclabel,relatime,data=ordered)
anestisb@khaos:[tmp]: adbWrap shell "dd if=/dev/block/mmcblk0p25 of=/data/local/tmp/system.img.raw bs=1024"
1048576+0 records in
1048576+0 records out
1073741824 bytes transferred in 46.821 secs (22932910 bytes/sec)
anestisb@khaos:[tmp]: adbWrap pull /data/local/tmp/system.img.raw .
7336 KB/s (1073741824 bytes in 142.935s)
anestisb@khaos:[tmp]: img2simg system.img.raw system.img.sparse
anestisb@khaos:[tmp]: simg_dump.py system.img.sparse
system.img.sparse: Total of 262144 4096-byte output blocks in 568 input chunks.
anestisb@khaos:[tmp]: file system.img.*
system.img.raw:    Linux rev 1.0 ext4 filesystem data, UUID=da594c53-9beb-f85c-85c5-cedf76546f7a, volume name "system" (needs journal recovery) (extents) (large files)
system.img.sparse: Android sparse image, version: 1.0, Total of 262144 4096-byte output blocks in 568 input chunks.
anestisb@khaos:[tmp]: du system.img.*
2097152	system.img.raw
798016	system.img.sparse
```

**Comment by dgadelha** [comment] 2016-01-07 22:15
Did you try to flash the sparse image with fastboot?

**Comment by anestisb** [comment] 2016-01-08 15:26
Yup you're right img2simg is broken for most devices since it fails to populate chunks correctly. Have just checked with upstream and no updates exist, so it affects AOSP too. Feel free to open a bug report at Android project and copy the ID/URL here to trace the issue. Will also have a deeper look later and follow-up in case the fix is easy.

Until further notice img2simg is disabled at commit https://github.com/anestisb/android-simg2img/commit/c125046af9250474dbfed1c68a11beaa5bb666c6

For devices where the bug is triggered you can either flash the raw image or use "mkuserimg.sh" from AOSP upstream in case you want to distribute images with smaller size.

**Comment by dgadelha** [comment] 2016-01-08 15:29
I'm not familiar with Google system of bug reporting, can you help me to open a bug report?

**Comment by anestisb** [comment] 2016-01-08 15:50
AOSP bugs can be reported [here](https://code.google.com/p/android/issues/list).

The steps to reproduce against a recent master branch are:
```
$ . build/envsetup.sh
$ lunch aosp_hammerhead-userdebug
$ mmma -j4 system/core/libsparse/
$ out/host/darwin-x86/bin/simg2img /tmp/system.img /tmp/system.img.raw
$ out/host/darwin-x86/bin/img2simg /tmp/system.img.raw /tmp/system.img.sparse
$ out/host/darwin-x86/bin/simg_dump.py -v /tmp/system.img | head -1
/tmp/system.img: Total of 215040 4096-byte output blocks in 1538 input chunks.
$ out/host/darwin-x86/bin/simg_dump.py -v /tmp/system.img.sparse | head -1
/tmp/system.img.sparse: Total of 215040 4096-byte output blocks in 1223 input chunks.
```

The difference in number of chunks for same image and same block-size, combined with rest of simg_dump.py output, is a good indicator of the bug. And of course the fastboot messages when flushing the invalid sparge img.

**Comment by dgadelha** [comment] 2016-01-08 16:17
Issue #198547 (https://code.google.com/p/android/issues/detail?id=198547) has been reported.
Thanks for the help.

**Comment by anestisb** [comment] 2016-01-15 13:45
Have confirmed that is bootloader limitation and not tool problem. Reverting last commit with img2simg target disable. Closing bug.

**Closed by anestisb** 2016-01-15 13:45 UTC
Labels: bug
